// Generated by CoffeeScript 1.7.1
(function() {
  var SBCL, fs, path, spawn;

  spawn = require('child_process').spawn;

  fs = require('fs');

  path = require('path');

  SBCL = (function() {
    function SBCL(fpath) {
      var cmd, exePath;
      exePath = path.join(path.dirname(fpath), (path.basename(fpath, '.lisp')) + '.exe');
      if (fs.exists(exePath)) {
        cmd = spawn(exePath);
        cmd.stdin.setEncoding('utf-8');
        cmd.stdout.setEncoding('utf-8');
        this.stdin = cmd.stdin;
        this.stdout = cmd.stdout;
      } else {
        cmd = spawn('sbcl', ['--script', fpath]);
        cmd.stdin.setEncoding('utf-8');
        cmd.stdout.setEncoding('utf-8');
        this.stdin = cmd.stdin;
        this.stdout = cmd.stdout;
      }
    }

    SBCL.prototype.write = function(str) {
      this.stdin.write(str);
      return this.stdin.end();
    };

    SBCL.prototype.use = function(fn) {
      var stdout;
      stdout = '';
      this.stdout.on('data', function(data) {
        return stdout += data;
      });
      return this.stdout.on('end', function() {
        return fn(stdout.replace(/NIL/g, ''));
      });
    };

    return SBCL;

  })();

  exports.SBCL = SBCL;

}).call(this);
